# Funding options for FiscalPilot
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [meetpandya27]

# Other platforms (uncomment and configure as needed)
# patreon: fiscalpilot
# open_collective: fiscalpilot
# ko_fi: fiscalpilot
# buy_me_a_coffee: fiscalpilot

# Custom links
# custom: ["https://fiscalpilot.dev/sponsor"]
