"""
Markdown report exporter.

Generates a beautiful Markdown report from an AuditReport,
suitable for GitHub, Notion, or any Markdown viewer.
"""

from __future__ import annotations

from fiscalpilot.models.report import AuditReport, Severity


def render_markdown(report: AuditReport) -> str:
    """Render an AuditReport as Markdown."""
    lines: list[str] = []

    # Header
    lines.append(f"# 🛫 FiscalPilot Audit Report — {report.company_name}")
    lines.append("")
    lines.append(f"*Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}*")
    if report.period_start and report.period_end:
        lines.append(f"*Period: {report.period_start} to {report.period_end}*")
    lines.append("")

    # Executive Summary
    summary = report.executive_summary
    lines.append("## 📊 Executive Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| **Total Findings** | {summary.total_findings} |")
    lines.append(f"| **Critical Issues** | {summary.critical_findings} |")
    lines.append(f"| **Potential Savings** | ${summary.total_potential_savings:,.2f} |")
    lines.append(f"| **Financial Health Score** | {summary.health_score}/100 |")
    lines.append("")

    if summary.narrative:
        lines.append(summary.narrative)
        lines.append("")

    # Findings by severity
    severity_emoji = {
        Severity.CRITICAL: "🔴",
        Severity.HIGH: "🟠",
        Severity.MEDIUM: "🟡",
        Severity.LOW: "🟢",
        Severity.INFO: "ℹ️",
    }

    lines.append("## 🔍 Findings")
    lines.append("")

    for severity in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
        findings = [f for f in report.findings if f.severity == severity]
        if not findings:
            continue

        emoji = severity_emoji[severity]
        lines.append(f"### {emoji} {severity.value.title()} ({len(findings)})")
        lines.append("")

        for finding in findings:
            lines.append(f"#### {finding.title}")
            lines.append("")
            lines.append(f"**Category:** {finding.category.value} | **Confidence:** {finding.confidence:.0%} | **Potential Savings:** ${finding.potential_savings:,.2f}")
            lines.append("")
            lines.append(finding.description)
            lines.append("")

            if finding.evidence:
                lines.append("**Evidence:**")
                for ev in finding.evidence:
                    lines.append(f"- {ev}")
                lines.append("")

            if finding.recommendation:
                lines.append(f"**Recommendation:** {finding.recommendation}")
                lines.append("")

            lines.append("---")
            lines.append("")

    # Action Items
    if report.action_items:
        lines.append("## ✅ Action Items")
        lines.append("")
        lines.append("| # | Action | Priority | Est. Savings | Effort |")
        lines.append("|---|--------|----------|-------------|--------|")
        for i, item in enumerate(report.action_items, 1):
            lines.append(
                f"| {i} | {item.title} | {item.priority.value} | "
                f"${item.estimated_savings:,.2f} | {item.effort} |"
            )
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Report generated by [FiscalPilot](https://github.com/fiscalpilot/fiscalpilot) — The Open-Source AI Financial Copilot*")

    return "\n".join(lines)
